// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -package taskdlq -source interface.go -destination interface_mock.go -self_package github.com/uber/cadence/service/history/dlq
//

// package taskdlq is a generated GoMock package.
package taskdlq

import (
	context "context"
	reflect "reflect"

	persistence "github.com/uber/cadence/common/persistence"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// DeleteTasks mocks base method.
func (m *MockStore) DeleteTasks(ctx context.Context, request DeleteTasksRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTasks", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTasks indicates an expected call of DeleteTasks.
func (mr *MockStoreMockRecorder) DeleteTasks(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTasks", reflect.TypeOf((*MockStore)(nil).DeleteTasks), ctx, request)
}

// GetAckLevels mocks base method.
func (m *MockStore) GetAckLevels(ctx context.Context, shardID int) ([]AckLevel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAckLevels", ctx, shardID)
	ret0, _ := ret[0].([]AckLevel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAckLevels indicates an expected call of GetAckLevels.
func (mr *MockStoreMockRecorder) GetAckLevels(ctx, shardID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAckLevels", reflect.TypeOf((*MockStore)(nil).GetAckLevels), ctx, shardID)
}

// GetAckLevelsForPartition mocks base method.
func (m *MockStore) GetAckLevelsForPartition(ctx context.Context, shardID int, domainID, clusterAttributeScope, clusterAttributeName string) ([]AckLevel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAckLevelsForPartition", ctx, shardID, domainID, clusterAttributeScope, clusterAttributeName)
	ret0, _ := ret[0].([]AckLevel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAckLevelsForPartition indicates an expected call of GetAckLevelsForPartition.
func (mr *MockStoreMockRecorder) GetAckLevelsForPartition(ctx, shardID, domainID, clusterAttributeScope, clusterAttributeName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAckLevelsForPartition", reflect.TypeOf((*MockStore)(nil).GetAckLevelsForPartition), ctx, shardID, domainID, clusterAttributeScope, clusterAttributeName)
}

// GetTasks mocks base method.
func (m *MockStore) GetTasks(ctx context.Context, request GetTasksRequest) (GetTasksResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasks", ctx, request)
	ret0, _ := ret[0].(GetTasksResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasks indicates an expected call of GetTasks.
func (mr *MockStoreMockRecorder) GetTasks(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasks", reflect.TypeOf((*MockStore)(nil).GetTasks), ctx, request)
}

// UpdateAckLevel mocks base method.
func (m *MockStore) UpdateAckLevel(ctx context.Context, request UpdateAckLevelRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAckLevel", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAckLevel indicates an expected call of UpdateAckLevel.
func (mr *MockStoreMockRecorder) UpdateAckLevel(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAckLevel", reflect.TypeOf((*MockStore)(nil).UpdateAckLevel), ctx, request)
}

// MockTaskExecutor is a mock of TaskExecutor interface.
type MockTaskExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockTaskExecutorMockRecorder
	isgomock struct{}
}

// MockTaskExecutorMockRecorder is the mock recorder for MockTaskExecutor.
type MockTaskExecutorMockRecorder struct {
	mock *MockTaskExecutor
}

// NewMockTaskExecutor creates a new mock instance.
func NewMockTaskExecutor(ctrl *gomock.Controller) *MockTaskExecutor {
	mock := &MockTaskExecutor{ctrl: ctrl}
	mock.recorder = &MockTaskExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskExecutor) EXPECT() *MockTaskExecutorMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockTaskExecutor) Execute(ctx context.Context, task persistence.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockTaskExecutorMockRecorder) Execute(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockTaskExecutor)(nil).Execute), ctx, task)
}
