// Code generated by gowrap. DO NOT EDIT.
// template: ../templates/ratelimited.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package ratelimited

import (
	"context"

	"github.com/uber/cadence/common/persistence"
	_sourcePersistence "github.com/uber/cadence/common/persistence"
	"github.com/uber/cadence/common/quotas"
)

// ratelimitedAsyncWorkflowQueueManager implements _sourcePersistence.AsyncWorkflowQueueManager interface instrumented with rate limiter.
type ratelimitedAsyncWorkflowQueueManager struct {
	wrapped      _sourcePersistence.AsyncWorkflowQueueManager
	rateLimiter  quotas.Limiter
	callerBypass quotas.CallerBypass
}

// NewAsyncWorkflowQueueManager creates a new instance of AsyncWorkflowQueueManager with ratelimiter.
func NewAsyncWorkflowQueueManager(
	wrapped persistence.AsyncWorkflowQueueManager,
	rateLimiter quotas.Limiter,
	callerBypass quotas.CallerBypass,
) persistence.AsyncWorkflowQueueManager {
	return &ratelimitedAsyncWorkflowQueueManager{
		wrapped:      wrapped,
		rateLimiter:  rateLimiter,
		callerBypass: callerBypass,
	}
}

func (c *ratelimitedAsyncWorkflowQueueManager) Close() {
	c.wrapped.Close()
	return
}

func (c *ratelimitedAsyncWorkflowQueueManager) Enqueue(ctx context.Context, request *_sourcePersistence.EnqueueAsyncWorkflowMessageRequest) (ep1 *_sourcePersistence.EnqueueAsyncWorkflowMessageResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.Enqueue(ctx, request)
}

func (c *ratelimitedAsyncWorkflowQueueManager) EnqueueToDLQ(ctx context.Context, request *_sourcePersistence.EnqueueAsyncWorkflowMessageRequest) (ep1 *_sourcePersistence.EnqueueAsyncWorkflowMessageResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.EnqueueToDLQ(ctx, request)
}

func (c *ratelimitedAsyncWorkflowQueueManager) GetAckLevel(ctx context.Context, request *_sourcePersistence.GetAsyncWorkflowAckLevelRequest) (gp1 *_sourcePersistence.GetAsyncWorkflowAckLevelResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.GetAckLevel(ctx, request)
}

func (c *ratelimitedAsyncWorkflowQueueManager) RangeDeleteMessages(ctx context.Context, request *_sourcePersistence.RangeDeleteAsyncWorkflowMessagesRequest) (err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.RangeDeleteMessages(ctx, request)
}

func (c *ratelimitedAsyncWorkflowQueueManager) RangeDeleteMessagesFromDLQ(ctx context.Context, request *_sourcePersistence.RangeDeleteAsyncWorkflowMessagesRequest) (err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.RangeDeleteMessagesFromDLQ(ctx, request)
}

func (c *ratelimitedAsyncWorkflowQueueManager) ReadMessages(ctx context.Context, request *_sourcePersistence.ReadAsyncWorkflowMessagesRequest) (rp1 *_sourcePersistence.ReadAsyncWorkflowMessagesResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.ReadMessages(ctx, request)
}

func (c *ratelimitedAsyncWorkflowQueueManager) ReadMessagesFromDLQ(ctx context.Context, request *_sourcePersistence.ReadAsyncWorkflowMessagesRequest) (rp1 *_sourcePersistence.ReadAsyncWorkflowMessagesResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.ReadMessagesFromDLQ(ctx, request)
}

func (c *ratelimitedAsyncWorkflowQueueManager) UpdateAckLevel(ctx context.Context, request *_sourcePersistence.UpdateAsyncWorkflowAckLevelRequest) (err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.UpdateAckLevel(ctx, request)
}
