// Code generated by gowrap. DO NOT EDIT.
// template: ../templates/metered.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package metered

import (
	"context"

	"github.com/uber/cadence/common/config"
	"github.com/uber/cadence/common/log"
	"github.com/uber/cadence/common/metrics"
	"github.com/uber/cadence/common/persistence"
	_sourcePersistence "github.com/uber/cadence/common/persistence"
)

// meteredAsyncWorkflowQueueManager implements _sourcePersistence.AsyncWorkflowQueueManager interface instrumented with rate limiter.
type meteredAsyncWorkflowQueueManager struct {
	base
	wrapped _sourcePersistence.AsyncWorkflowQueueManager
}

// NewAsyncWorkflowQueueManager creates a new instance of AsyncWorkflowQueueManager with ratelimiter.
func NewAsyncWorkflowQueueManager(
	wrapped persistence.AsyncWorkflowQueueManager,
	metricClient metrics.Client,
	logger log.Logger,
	cfg *config.Persistence,
) persistence.AsyncWorkflowQueueManager {
	return &meteredAsyncWorkflowQueueManager{
		wrapped: wrapped,
		base: base{
			metricClient:                  metricClient,
			logger:                        logger,
			enableLatencyHistogramMetrics: cfg.EnablePersistenceLatencyHistogramMetrics,
			hostName:                      cfg.HostName,
		},
	}
}

func (c *meteredAsyncWorkflowQueueManager) Close() {
	c.wrapped.Close()
	return
}

func (c *meteredAsyncWorkflowQueueManager) Enqueue(ctx context.Context, request *_sourcePersistence.EnqueueAsyncWorkflowMessageRequest) (ep1 *_sourcePersistence.EnqueueAsyncWorkflowMessageResponse, err error) {
	op := func() error {
		ep1, err = c.wrapped.Enqueue(ctx, request)
		c.emptyMetric("AsyncWorkflowQueueManager.Enqueue", request, ep1, err)
		return err
	}

	err = c.call(metrics.PersistenceEnqueueScope, op, getCustomMetricTags(request)...)
	return
}

func (c *meteredAsyncWorkflowQueueManager) EnqueueToDLQ(ctx context.Context, request *_sourcePersistence.EnqueueAsyncWorkflowMessageRequest) (ep1 *_sourcePersistence.EnqueueAsyncWorkflowMessageResponse, err error) {
	op := func() error {
		ep1, err = c.wrapped.EnqueueToDLQ(ctx, request)
		c.emptyMetric("AsyncWorkflowQueueManager.EnqueueToDLQ", request, ep1, err)
		return err
	}

	err = c.call(metrics.PersistenceEnqueueToDLQScope, op, getCustomMetricTags(request)...)
	return
}

func (c *meteredAsyncWorkflowQueueManager) GetAckLevel(ctx context.Context, request *_sourcePersistence.GetAsyncWorkflowAckLevelRequest) (gp1 *_sourcePersistence.GetAsyncWorkflowAckLevelResponse, err error) {
	op := func() error {
		gp1, err = c.wrapped.GetAckLevel(ctx, request)
		c.emptyMetric("AsyncWorkflowQueueManager.GetAckLevel", request, gp1, err)
		return err
	}

	err = c.call(metrics.PersistenceGetAckLevelScope, op, getCustomMetricTags(request)...)
	return
}

func (c *meteredAsyncWorkflowQueueManager) RangeDeleteMessages(ctx context.Context, request *_sourcePersistence.RangeDeleteAsyncWorkflowMessagesRequest) (err error) {
	op := func() error {
		err = c.wrapped.RangeDeleteMessages(ctx, request)
		c.emptyMetric("AsyncWorkflowQueueManager.RangeDeleteMessages", request, err, err)
		return err
	}

	err = c.call(metrics.PersistenceRangeDeleteMessagesScope, op, getCustomMetricTags(request)...)
	return
}

func (c *meteredAsyncWorkflowQueueManager) RangeDeleteMessagesFromDLQ(ctx context.Context, request *_sourcePersistence.RangeDeleteAsyncWorkflowMessagesRequest) (err error) {
	op := func() error {
		err = c.wrapped.RangeDeleteMessagesFromDLQ(ctx, request)
		c.emptyMetric("AsyncWorkflowQueueManager.RangeDeleteMessagesFromDLQ", request, err, err)
		return err
	}

	err = c.call(metrics.PersistenceRangeDeleteMessagesFromDLQScope, op, getCustomMetricTags(request)...)
	return
}

func (c *meteredAsyncWorkflowQueueManager) ReadMessages(ctx context.Context, request *_sourcePersistence.ReadAsyncWorkflowMessagesRequest) (rp1 *_sourcePersistence.ReadAsyncWorkflowMessagesResponse, err error) {
	op := func() error {
		rp1, err = c.wrapped.ReadMessages(ctx, request)
		c.emptyMetric("AsyncWorkflowQueueManager.ReadMessages", request, rp1, err)
		return err
	}

	err = c.call(metrics.PersistenceReadMessagesScope, op, getCustomMetricTags(request)...)
	return
}

func (c *meteredAsyncWorkflowQueueManager) ReadMessagesFromDLQ(ctx context.Context, request *_sourcePersistence.ReadAsyncWorkflowMessagesRequest) (rp1 *_sourcePersistence.ReadAsyncWorkflowMessagesResponse, err error) {
	op := func() error {
		rp1, err = c.wrapped.ReadMessagesFromDLQ(ctx, request)
		c.emptyMetric("AsyncWorkflowQueueManager.ReadMessagesFromDLQ", request, rp1, err)
		return err
	}

	err = c.call(metrics.PersistenceReadMessagesFromDLQScope, op, getCustomMetricTags(request)...)
	return
}

func (c *meteredAsyncWorkflowQueueManager) UpdateAckLevel(ctx context.Context, request *_sourcePersistence.UpdateAsyncWorkflowAckLevelRequest) (err error) {
	op := func() error {
		err = c.wrapped.UpdateAckLevel(ctx, request)
		c.emptyMetric("AsyncWorkflowQueueManager.UpdateAckLevel", request, err, err)
		return err
	}

	err = c.call(metrics.PersistenceUpdateAckLevelScope, op, getCustomMetricTags(request)...)
	return
}
