// Code generated by gowrap. DO NOT EDIT.
// template: ../templates/errorinjector.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package errorinjectors

import (
	"context"
	"time"

	"github.com/uber/cadence/common/log"
	"github.com/uber/cadence/common/persistence"
	_sourcePersistence "github.com/uber/cadence/common/persistence"
)

// injectorAsyncWorkflowQueueManager implements _sourcePersistence.AsyncWorkflowQueueManager interface instrumented with error injection.
type injectorAsyncWorkflowQueueManager struct {
	wrapped   _sourcePersistence.AsyncWorkflowQueueManager
	starttime time.Time
	errorRate float64
	logger    log.Logger
}

// NewAsyncWorkflowQueueManager creates a new instance of AsyncWorkflowQueueManager with error injection.
func NewAsyncWorkflowQueueManager(
	wrapped persistence.AsyncWorkflowQueueManager,
	errorRate float64,
	logger log.Logger,
	starttime time.Time,
) persistence.AsyncWorkflowQueueManager {
	return &injectorAsyncWorkflowQueueManager{
		wrapped:   wrapped,
		starttime: starttime,
		errorRate: errorRate,
		logger:    logger,
	}
}

func (c *injectorAsyncWorkflowQueueManager) Close() {
	c.wrapped.Close()
	return
}

func (c *injectorAsyncWorkflowQueueManager) Enqueue(ctx context.Context, request *_sourcePersistence.EnqueueAsyncWorkflowMessageRequest) (ep1 *_sourcePersistence.EnqueueAsyncWorkflowMessageResponse, err error) {
	fakeErr := generateFakeError(c.errorRate, c.starttime)
	var forwardCall bool
	if forwardCall = shouldForwardCallToPersistence(fakeErr); forwardCall {
		ep1, err = c.wrapped.Enqueue(ctx, request)
	}

	if fakeErr != nil {
		logErr(c.logger, "AsyncWorkflowQueueManager.Enqueue", fakeErr, forwardCall, err)
		err = fakeErr
		return
	}
	return
}

func (c *injectorAsyncWorkflowQueueManager) EnqueueToDLQ(ctx context.Context, request *_sourcePersistence.EnqueueAsyncWorkflowMessageRequest) (ep1 *_sourcePersistence.EnqueueAsyncWorkflowMessageResponse, err error) {
	fakeErr := generateFakeError(c.errorRate, c.starttime)
	var forwardCall bool
	if forwardCall = shouldForwardCallToPersistence(fakeErr); forwardCall {
		ep1, err = c.wrapped.EnqueueToDLQ(ctx, request)
	}

	if fakeErr != nil {
		logErr(c.logger, "AsyncWorkflowQueueManager.EnqueueToDLQ", fakeErr, forwardCall, err)
		err = fakeErr
		return
	}
	return
}

func (c *injectorAsyncWorkflowQueueManager) GetAckLevel(ctx context.Context, request *_sourcePersistence.GetAsyncWorkflowAckLevelRequest) (gp1 *_sourcePersistence.GetAsyncWorkflowAckLevelResponse, err error) {
	fakeErr := generateFakeError(c.errorRate, c.starttime)
	var forwardCall bool
	if forwardCall = shouldForwardCallToPersistence(fakeErr); forwardCall {
		gp1, err = c.wrapped.GetAckLevel(ctx, request)
	}

	if fakeErr != nil {
		logErr(c.logger, "AsyncWorkflowQueueManager.GetAckLevel", fakeErr, forwardCall, err)
		err = fakeErr
		return
	}
	return
}

func (c *injectorAsyncWorkflowQueueManager) RangeDeleteMessages(ctx context.Context, request *_sourcePersistence.RangeDeleteAsyncWorkflowMessagesRequest) (err error) {
	fakeErr := generateFakeError(c.errorRate, c.starttime)
	var forwardCall bool
	if forwardCall = shouldForwardCallToPersistence(fakeErr); forwardCall {
		err = c.wrapped.RangeDeleteMessages(ctx, request)
	}

	if fakeErr != nil {
		logErr(c.logger, "AsyncWorkflowQueueManager.RangeDeleteMessages", fakeErr, forwardCall, err)
		err = fakeErr
		return
	}
	return
}

func (c *injectorAsyncWorkflowQueueManager) RangeDeleteMessagesFromDLQ(ctx context.Context, request *_sourcePersistence.RangeDeleteAsyncWorkflowMessagesRequest) (err error) {
	fakeErr := generateFakeError(c.errorRate, c.starttime)
	var forwardCall bool
	if forwardCall = shouldForwardCallToPersistence(fakeErr); forwardCall {
		err = c.wrapped.RangeDeleteMessagesFromDLQ(ctx, request)
	}

	if fakeErr != nil {
		logErr(c.logger, "AsyncWorkflowQueueManager.RangeDeleteMessagesFromDLQ", fakeErr, forwardCall, err)
		err = fakeErr
		return
	}
	return
}

func (c *injectorAsyncWorkflowQueueManager) ReadMessages(ctx context.Context, request *_sourcePersistence.ReadAsyncWorkflowMessagesRequest) (rp1 *_sourcePersistence.ReadAsyncWorkflowMessagesResponse, err error) {
	fakeErr := generateFakeError(c.errorRate, c.starttime)
	var forwardCall bool
	if forwardCall = shouldForwardCallToPersistence(fakeErr); forwardCall {
		rp1, err = c.wrapped.ReadMessages(ctx, request)
	}

	if fakeErr != nil {
		logErr(c.logger, "AsyncWorkflowQueueManager.ReadMessages", fakeErr, forwardCall, err)
		err = fakeErr
		return
	}
	return
}

func (c *injectorAsyncWorkflowQueueManager) ReadMessagesFromDLQ(ctx context.Context, request *_sourcePersistence.ReadAsyncWorkflowMessagesRequest) (rp1 *_sourcePersistence.ReadAsyncWorkflowMessagesResponse, err error) {
	fakeErr := generateFakeError(c.errorRate, c.starttime)
	var forwardCall bool
	if forwardCall = shouldForwardCallToPersistence(fakeErr); forwardCall {
		rp1, err = c.wrapped.ReadMessagesFromDLQ(ctx, request)
	}

	if fakeErr != nil {
		logErr(c.logger, "AsyncWorkflowQueueManager.ReadMessagesFromDLQ", fakeErr, forwardCall, err)
		err = fakeErr
		return
	}
	return
}

func (c *injectorAsyncWorkflowQueueManager) UpdateAckLevel(ctx context.Context, request *_sourcePersistence.UpdateAsyncWorkflowAckLevelRequest) (err error) {
	fakeErr := generateFakeError(c.errorRate, c.starttime)
	var forwardCall bool
	if forwardCall = shouldForwardCallToPersistence(fakeErr); forwardCall {
		err = c.wrapped.UpdateAckLevel(ctx, request)
	}

	if fakeErr != nil {
		logErr(c.logger, "AsyncWorkflowQueueManager.UpdateAckLevel", fakeErr, forwardCall, err)
		err = fakeErr
		return
	}
	return
}
